version: "3.4"
services:
  web:
    #container_name: web-app
    build: 
      dockerfile: Dockerfile
      context: MvcApp
    ports:
      - "8000"
    environment:
      ConnectionStrings__ProductsContext: "Server=db;Database=ProductsDB;User=sa;Password=@Aa123456;Trusted_Connection=False;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "85:80"

  db:
    container_name: mssql-db
    image: "mcr.microsoft.com/mssql/server:2019-CU4-ubuntu-16.04" #"microsoft/mssql-server-linux"
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "@Aa123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"